# server port
server:
  port: 8080

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost/board"
    username: "root"
    password: "Sujeong88*"

# MyBatis
mybatis:
  mapper-locations: "classpath:mapper/*.xml"
  config-location: "classpath:mybatis-config.xml"
#  type-aliases-package: com.practice.board.dto

